import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import ClientLayout from "./ClientLayout";

export const metadata: Metadata = {
  title: "Flicktionary",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "./../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientLayout
      fontVariable={pretendard.variable}
      fontClassName={pretendard.className}
    >
      {children}
    </ClientLayout>
  );
}
